### ISSUE TITLE
Orbbec Astra(not Pro)

### ISSUE THREAD

**Issue by yutakaoka** [fabianschenk/REVO#2]
Hi,

I have one question about Orbbec Astra sensor.
Can I use Orbbec Astra? Is it for Pro version only for now?
If we use only VGA, it seems like we can use both.

Thanks,
Yutaka

**Comment by fabianschenk** [comment]
Hi!
I use the Orbbec Astra Pro sensor also only with VGA resolution, so this shouldn't be problem.
Sadly, I don't have a non-pro Orbbec Astra so I can't try. 
If it doesn't work out of the box, you could try to access the non-pro Orbbec Astra with OpenNI only, which allegedly works according to the Orbbec engineers. This should only take some slight modifications in the code.
This should be very similar to the [NIViewer](https://github.com/orbbec/OpenNI2/blob/master/Source/Tools/NiViewer).

Fabian

**Comment by fabianschenk** [comment]
I've finally gotten hold of a (non-pro) Orbbec Astra sensor. REVO now supports the (non-pro) sensor via an OpenNI interface! Just compile the current version with WITH_ORBBEC_OPENNI and in the config file set INPUT_TYPE: 3 (example file can be found in the config directory). However, in my test runs I noticed that the image quality @640x480 is far worse than that of the pro version.
