### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by edgar-explorer** [fabianschenk/REVO#3]
Thank for your excellent work. I encountered an error when use camke.. ,enven through I installed ffmpeg. 
c@cc-K55VD:~/code/REVO-master/build$ cmake ..
cmake: /home/cc/code/REVO-master/ThirdParty/libuvc/build/CMakeFiles
-- The compiler /usr/bin/c++ has C++11 support. Please use a different C++ compiler.
CMake Error at CMakeLists.txt:100 (include):
  include could not find load file:

    cmake/external_FFMPEG.cmake

OpenCV: /opt/ros/kinetic/include/opencv-3.3.1-dev;/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv
Eigen found: /usr/include/eigen3  
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
libuvc_LIBRARIES: , pangolin;realsense;/home/cc/code/REVO-master/orbbec_astra_pro/drivers/libOpenNI2.so;opencv_core;opencv_videoio;opencv_imgcodecs;opencv_imgproc;opencv_calib3d;opencv_highgui;/usr/lib/x86_64-linux-gnu/libboost_filesystem.so;/usr/lib/x86_64-linux-gnu/libboost_system.so
-- Configuring incomplete, errors occurred!
See also "/home/cc/code/REVO-master/build/CMakeFiles/CMakeOutput.log".
Can you provide clear dependencies?

**Comment by fabianschenk** [comment]
Hi!
I implemented the FFMPEG support kind of recently and apparently forgot to commit cmake/external_FFMPEG.cmake. I just added the missing file and tested it on my system. It should work now.
Please note that you also have to copy the Orbbec Astra Pro driver to orbbec_astra_pro directory! 
If you don't need Orbbec Astra Pro support, you can deactivate it.
